name: Security Audit Workflow

on: [push, pull_request]

jobs:
  security-audit: #  Nom du job (identifiant)
    name: Security Audit #  Nom affiché du job
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2
    
      - name: Set up Composer cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cachedir)" >> $GITHUB_ENV

      - name: Caching dependencies
        uses: actions/cache@v4
        with:
            path: ${{ env.COMPOSER_CACHE_DIR }}
            key: php8.3-${{ hashFiles('**/composer.json') }}
            restore-keys: |
                php8.3-composer-latest
    
      - name: Update composer
        run: composer self-update

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run security audit
        run: composer audit \
            --no-dev \
            --abandoned="report" \
            --ignore-severity="low" \
            --format="json" \
            --no-ansi \
            > /tmp/security-audit.json


    ## Optional: UNIQUEMENT SUR LES PROJETS SYMFONY
      - name: Run security audit with Sensiolabs Security Checker
        run: composer security:check

      - name: Upload security audit report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-audit
          path: /tmp/security-audit.json
