name: Security Audit

on: [push, pull_request, workflow_call]

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2

      - run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.3-${{ hashFiles('**/composer.lock') }}
          restore-keys: php8.3-composer-

      - run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - run: |
          composer audit \
            --no-dev \
            --abandoned=report \
            --ignore-severity=low \
            --format=json \
            --no-ansi > /tmp/security-audit.json

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-audit-${{ github.run_id }}
          path: /tmp/security-audit.json
          retention-days: 30
