name: Code Quality

on: [push, pull_request, workflow_call]

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2

      - run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.3-${{ hashFiles('**/composer.lock') }}
          restore-keys: php8.3-composer-

      - run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - run: composer app:code-quality
