name: Code Testing Workflow

#on: [push, pull_request]

on:
  workflow_call:


jobs:
  code-testing:
    name: Code Testing
    runs-on: ubuntu-latest
    continue-on-error: false

    services:
      database:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: symfony_ci_cd_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2

      - name: Set up Composer cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Caching dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.3-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php8.3-composer-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run Composer security audit
        run: |
          composer audit \
            --no-dev \
            --abandoned=report \
            --ignore-severity=low \
            --format=json \
            --no-ansi \
            > /tmp/security-audit.json

      - name: Upload security audit report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-audit-${{ github.run_id }}
          path: /tmp/security-audit.json
          retention-days: 30

      - name: Run database migrations and tests
        run: composer app:tests
        env:
          APP_ENV: test
          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/symfony_ci_cd?serverVersion=8.0.32&charset=utf8mb4"
